### ISSUE TITLE
"GarageDoorOpener" device type not supported

### ISSUE THREAD

**Issue by jebware** [jbnunn/Alexa-MyQGarage#1]
When I list devices on the MyQ API, I don't have one where `dev["MyQDeviceTypeName"] == "VGDO"` but I do have one of type `"GarageDoorOpener"`, and I was able to get this script to work with that device.  I'm assuming this is due to some difference in my hardware setup.

I'm going to submit a PR so the script will support a device with either type.  Thanks!

**Comment by jbnunn** [comment]
Thanks @jebstuart
