### ISSUE TITLE
Update Directions

### ISSUE THREAD

**Issue by merkidemis** [jbnunn/Alexa-MyQGarage#10]
An additional step needs to be added for setting up the AWS Lambda function. At least as of  Oct 2016 you must select US East (N Virginia) for your AWS region to get the Skills Kit trigger option.

**Comment by CelticWebSolutions** [comment]
I had no issue selecting this in the UK using the Ireland (Europe) region.  I haven't got everything running yet but I was able to get the Trigger set without issue.  Unfortunately the system isn't working for me though so I'm assuming I've got something wrong somewhere :(

**Comment by jbnunn** [comment]
@CelticWebSolutions Look in the Monitoring tab of your Lambda function, click "View logs in CloudWatch," and see if you have any errors. Happy to help you debug if you find some.

**Comment by tomswift33** [comment]
This worked terrifically until a week ago.  I've changed the Wake Word to "Computer" and when I say "Computer, ask the garage door to open"  I get this response from Alexa: "There was a problem with the requested skill's response"
I tried troubleshooting and I'm getting the following error, in testing.  Can you help, please?:

Execution result: failed(logs)
The area below shows the result returned by your function execution.
{
  "stackTrace": [
    [
      "/var/task/main.py",
      31,
      "lambda_handler",
      "raise"
    ]
  ],
  "errorType": "TypeError",
  "errorMessage": "exceptions must be old-style classes or derived from BaseException, not NoneType"

**Comment by tomswift33** [comment]
This is from the lambda monitoring log:

START RequestId: 1cefd1a4-f099-11e6-84dc-754b7ce7650f Version: $LATEST
Invalid Application ID
exceptions must be old-style classes or derived from BaseException, not NoneType: TypeError
Traceback (most recent call last):
  File "/var/task/main.py", line 31, in lambda_handler
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

END RequestId: 1cefd1a4-f099-11e6-84dc-754b7ce7650f
REPORT RequestId: 1cefd1a4-f099-11e6-84dc-754b7ce7650f	Duration: 61.40 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 20 MB

**Comment by tigerbrain** [comment]
Hi @tomswift33, about a week ago, Chamberlain implemented an endpoint change that caused this code to fail, but @jbnunn has since corrected the issue and uploaded the updated code on his repository.  Please make sure that you download the latest code set and give it a try and see if the new main.py is working for you.

Thanks!

**Comment by tomswift33** [comment]
Thank you.  Tried new code and still getting an error:

START RequestId: 22b6bf62-f0b4-11e6-a134-35067f3d15ad Version: $LATEST
Invalid Application ID
exceptions must be old-style classes or derived from BaseException, not NoneType: TypeError
Traceback (most recent call last):
  File "/var/task/main.py", line 29, in lambda_handler
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

END RequestId: 22b6bf62-f0b4-11e6-a134-35067f3d15ad
REPORT RequestId: 22b6bf62-f0b4-11e6-a134-35067f3d15ad	Duration: 0.58 m

**Comment by jbnunn** [comment]
Hi @tomswift33  -- "Invalid Application ID" means you need to put in your Alexa Skills Kit ID on line 25. Can you try that?

**Comment by tomswift33** [comment]
I really appreciate your help

I started from scratch and followed the directions impeccably.   I'm still getting this error:

START RequestId: 4813a5aa-f155-11e6-9f89-036fe0a003ca Version: $LATEST
Invalid Application ID
exceptions must be old-style classes or derived from BaseException, not NoneType: TypeError
Traceback (most recent call last):
  File "/var/task/main.py", line 27, in lambda_handler
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

END RequestId: 4813a5aa-f155-11e6-9f89-036fe0a003ca
REPORT RequestId: 4813a5aa-f155-11e6-9f89-036fe0a003ca	Duration: 0.57 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 18 MB

**Comment by tigerbrain** [comment]
Hi @tomswift33, I am not really sure why you are experiencing that problem but my hunch is that you failed to edit the main.py file properly.  Another thing I can suggest is for you to use the code I posted here https://github.com/tigerbrain/Alexa-MyQ-WithMultiDoorSupport.  It is a variant of the code that jbnunn wrote with a different type of install step that doesn't require modifying the main.py file.  However, since the code is written for the purpose of supporting 2 doors, the command for asking Alexa to close the door is also slightly different.  Give this a try if you wish and see if it works better for you.  Thanks.

**Comment by McNouvion** [comment]
I actually ran in that issue today ... I did not spend much time investigating but I think the session data is not being set or session.application.applicationId is the wrong key to check against. I hardcoded the APP_ID and tried many things but in the end just disabled that check so I could play with the skill and it works ... Except for the part checking the skill_id equals the session application_id. Note I also updated the skill to use requests 2.13.x as I was trying to debug the issue.

Awesome job and thank you to the authors by the way!

**Comment by SConaway** [comment]
FYI the username/password must not be HTML-friendly, e.g. test@test.test, tE$t

**Comment by sjm01** [comment]
Have the same issue as tomswift33.  Also, followed tigerbrain suggestion and followed MultiDoor installation.  Still having the same problem:
exceptions must be old-style classes or derived from BaseException, not NoneType: TypeError
Traceback (most recent call last):
File "/var/task/main.py", line 26, in lambda_handler
raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

Any help will be appreciated.

**Comment by tigerbrain** [comment]
Hi @sjm01, are you certain that you are using the latest code from my multi door repository?  When did you download the code?  Also, regarding the error that you are facing, did you perform the test in your lambda function and got this error message or did you perform the test in the Alexa Skills Kit per the instructions I provided?

**Comment by sjm01** [comment]
- I downloaded the code yesterday.
- Got the error in the Alexa Skills Kit.

Note that I first tried the single door version and then the two door version.  Same issue with both.

Thanks.

**Comment by tigerbrain** [comment]
Hi @sjm01, please verify the following:
- user and password is NOT URL encrypted meaning that the "@" symbol needs to be written as is and not translated to "%.."
- if you tried to use the multi door version whereby editing the main.py is not needed, please make sure that you followed the step by step instructions thoroughly and started from scratch as their slight subtleties between the two instructions and I want to make sure that you didn't skip any steps.
- Lastly, to help troubleshoot your issue better, please share more details about your setup.  Is your MyQ built-in or is it separate from your garage opener?  If built-in, what's the brand name of your garage opener (i.e. Liftmaster, Chamberlain, etc.)

**Comment by sjm01** [comment]
tigerbrain,
- Have @ symbol in username
- Did not main.py for multi door version.  Followed the instructions step by step.
- My MyQ is separate from garage opener https://www.amazon.com/Chamberlain-MYQ-G0201-MyQ-Garage-Controls-Smartphone/dp/B00EAD65UW/ref=sr_1_1?ie=UTF8&qid=1488257869&sr=8-1&keywords=myq+garage+door+opener
- My Garage openers are Chamberlain and Craftsman

**Comment by tigerbrain** [comment]
Hi @sjm01, so we basically have a similar setup.  When you switched to the multi door setup, did you start from scratch?  Did you create a new Alexa Skills Kit and Lambda function?  If not, I suggest that you do start all over again and make sure you follow the instructions carefully as there are some subtleties between the two instructions that can be easily overlooked.  Also, would you mind sharing the value that you used for the skill_id variable (just hide the last 4 values)?  Make sure that variable names are all in lower case.

**Comment by sjm01** [comment]
Started all over.  Alexa responds "There was a problem with the requested skills response".
This time the CloudWatch log shows different error:  module initialization error: 'no_open'

My skills_id : amzn1.ask.skill.a38821c8-f72e-4efd-a836-1a8d8d1cXXXX (last four digit replaced with XXXX)

Thanks for looking into this

**Comment by tigerbrain** [comment]
Hi @sjm01, you will need to setup variable no_open even if you don't plan to use it.  you just need to make sure to set it up with a value of "N" minus the double quotes.

**Comment by tigerbrain** [comment]
Hi @sjm01, were you finally about to get this working?

**Comment by sjm01** [comment]
Success!
Thank you, thank you, thank you.

**Comment by tigerbrain** [comment]
Good to hear @sjm01.  Glad you get to finally enjoy this wonderful luxury thanks to @jbnunn!
