### ISSUE TITLE
Publicly publishable skill

### ISSUE THREAD

**Issue by james-powis** [jbnunn/Alexa-MyQGarage#15]
In the absence of MyQ having really any desire to release any integrations themselves, I am curious on if there is any desire to make this project "release capable", having worked through it, it would seem the only requirement to making this "user agnostic" is to provide an Alexa app interface for providing credentials... 

I am willing to help contribute to this end goal, as it feels like there is much angst by the less technical owners of the MyQ openers.

**Comment by jbnunn** [comment]
@james-powis Completely agree. Anything you want to do help would be great. I can't believe Chamberlain hasn't shown any interest in doing this themselves.
