### ISSUE TITLE
Login URI changed?

### ISSUE THREAD

**Issue by lawndart471** [jbnunn/Alexa-MyQGarage#20]
I'm not sure, but I think maybe the login/host URI might've changed? 

This has been working beautifully for the past month, but starting in the last day or two, I'm getting the following:

No JSON object could be decoded: ValueError Traceback (most recent call last): File "/var/task/main.py", line 32, in lambda_handler login() File "/var/task/main.py", line 89, in login response = requests.get(login_uri()).json() File "/var/task/requests/models.py", line 808, in json return complexjson.loads(self.text, **kwargs) File "/usr/lib64/python2.7/json/__init__.py", line
No JSON object could be decoded: ValueError
Traceback (most recent call last):
File "/var/task/main.py", line 32, in lambda_handler
login()
File "/var/task/main.py", line 89, in login
response = requests.get(login_uri()).json()
File "/var/task/requests/models.py", line 808, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
return _default_decoder.decode(s)
File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

If I'm reading that correctly, it appears I'm not able to log into the myq site? My login info hasn't changed. And, actually, both the site and my phone app still work. Just not Alexa. I've made no other changes to code, other than specified in the directions. Also, the directions only specified <MYQ_LOGIN_USERNAME> and <MYQ_LOGIN_PASSWORD> in main.py, not the additional fields including:

myq_userid
myq_security_token
myq_cached_login_response
myq_device_id

Thank you in advance for any guidance you can provide! I really appreciate the work that was done on this!

**Comment by ishan11** [comment]
Have you made the changes that were pushed last weekend? After making the changes I was able to get the skill to work again.

**Comment by lawndart471** [comment]
A. Your reply was insanely quick. Thanks!
B. Sadly, I have not. I should have probably checked first before posting here. I had not been monitoring for changes. Let me try that first. Thank you very much. This could be due to my own ignorance.

**Comment by lawndart471** [comment]
ANNNNDDDD... that was my problem... So, lesson learned... RTFM.
