### ISSUE TITLE
Door States dont work

### ISSUE THREAD

**Issue by SConaway** [jbnunn/Alexa-MyQGarage#22]
My door shows up as doorState = 1 if closed or opened

**Comment by SConaway** [comment]
The door is clearly closed, and the state is 1 if opened or closed
The code I'm using is 
[main.txt](https://github.com/jbnunn/Alexa-MyQGarage/files/778866/main.txt)
attached

and the request: 

`{
  "session": {
    "sessionId": "SessionId.1f02711e-a628-4d9d-a4a2-e805b5b3d43b",
    "application": {
      "applicationId": "amzn1.ask.skill.**********"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.***********"
    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.ea46cda3-9b09-4d33-ac74-ae98b991c0bb",
    "locale": "en-US",
    "timestamp": "2017-02-15T03:00:17Z",
    "intent": {
      "name": "StateIntent",
      "slots": {
        "doorstate": {
          "name": "doorstate",
          "value": "up"
        }
      }
    }
  },
  "version": "1.0"
}`

and the results from Lambda:

`{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "text": "Yes, your garage door is open",
      "type": "PlainText"
    },
    "shouldEndSession": true,
    "reprompt": {
      "outputSpeech": {
        "text": "I didn't understand that. You can say ask the garage door if it's open",
        "type": "PlainText"
      }
    },
    "card": {
      "content": "MyQ - Yes, your garage door is open",
      "type": "Simple",
      "title": "MyQ - Yes, your garage door is open"
    }
  },
  "sessionAttributes": {}
}`

**Comment by tigerbrain** [comment]
Hi @SConaway, I just created a pull request for @jbnunn to merge that should hopefully fix the issue that you are having.  Thanks!

**Comment by SConaway** [comment]
Thanks @tigerbrain it works perfectly
