### ISSUE TITLE
Chamberlain API change?

### ISSUE THREAD

**Issue by davecatmgr** [jbnunn/Alexa-MyQGarage#24]
Hey Guys,

I just installed the Chamberlain skill and it works great opening and closing the door.  One problem:  the skill always reports the door as open regardless of its actual position. (ie.  I ask if the garage door is open and it reports yes even though the door is closed.  The MyQ app from Chamberlain correctly knows the position so apparently the skill is not picking this up.  I created the skill with the latest updates and my garage door is brand new (WD1000WF).  Since the open/close commands work correctly. I am thinking maybe Chamberlain changed the door state api?

Any ideas would be very appreciated.

BTW. Thanks all for this skill.  It's awesome!

Dave
Friday Harbor, WA

**Comment by SConaway** [comment]
@davecatmgr try the pull request by @tigerbrain.  It works wonderfully!

**Comment by davecatmgr** [comment]
Wow!  That was fast...  OK, I'll see what I can find out.  Thanks SConaway

**Comment by SConaway** [comment]
No problem.  It works great

**Comment by davecatmgr** [comment]
Beautiful!  Well done, people.  Very much appreciated.  Thank you.

Dave

**Comment by SConaway** [comment]
You might want to close this now since @jbnunn merged @tigerbrain's. FYI
