### ISSUE TITLE
line 24 help

### ISSUE THREAD

**Issue by joshuadwallace** [jbnunn/Alexa-MyQGarage#30]
i have been playing with this trying to get it working for the last couple weeks. any help would be greatly appreciated. thank you

START RequestId: 2cff6fcb-0644-11e7-b64f-01b9fcbda5a0 Version: $LATEST
'session': KeyError
Traceback (most recent call last):
  File "/var/task/main.py", line 24, in lambda_handler
    if event['session']['application']['applicationId'] != "amzn1.ask.skill.bbdef27c-0f33-42d1-9a1c-00e7da37ecf9":
KeyError: 'session'

END RequestId: 2cff6fcb-0644-11e7-b64f-01b9fcbda5a0
REPORT RequestId: 2cff6fcb-0644-11e7-b64f-01b9fcbda5a0	Duration: 0.60 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 16 MB

**Comment by tigerbrain** [comment]
Hi @joshuadwallace.  I don't know why you are having this problem but a suggestion I can give is for you to start over following the step by step instruction document contained in one of the files included in the repository.  Also make sure that you download the latest files as there have been a lot of changes to some key files in February.

If following the step by step instruction document still leads you nowhere, try starting over a  second  time using my multidoor version that can be found in URL https://github.com/tigerbrain/Alexa-MyQ-WithMultiDoorSupport.  But be advised that you should follow the step by step instruction very carefully as there are some slight and subtle differences between the two installation methods that could easily be missed.

**Comment by joshuadwallace** [comment]
I started over with the multidoor and everything works perfect. Thank you very much I really appreciate it.
