### ISSUE TITLE
Door State is incorrect

### ISSUE THREAD

**Issue by dmcoleman79** [jbnunn/Alexa-MyQGarage#32]
Updated main.py got this skill working again for me but now when I ask alexa if my door is open and it isn't she says yes your garage door is open.  When I ask if it is closed when it is she says no your garage door is open.  Any ideas?

**Comment by tigerbrain** [comment]
Hi @dmcoleman79,

When did you download your code set?  The main.py file on the repository was last updated on Feb 18.  Are you sure you are using the updated code set?

**Comment by jbnunn** [comment]
Closing, seems to be correct
