### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by jomizrahi92** [jbnunn/Alexa-MyQGarage#38]
Getting an error when calling alexa, `The SpeechletResponse must not be null`. Followed all instructions. Can't seem to get it working. Want to make sure everything is correct and still working.

**Comment by SConaway** [comment]
It worked 1 minute ago for me. What gave you the error? The Echo itself?

**Comment by jomizrahi92** [comment]
Yes on the echo app it shows that error.

**Comment by SConaway** [comment]
That's weird. Try typing in `Alexa, ask the garage door to close` on the testing tab of the Skill Configuration: 
![screen shot 2018-03-05 at 8 54 37 pm](https://user-images.githubusercontent.com/20807660/37014768-c17bb0e6-20b7-11e8-9ded-48f4c4313d95.png)

**Comment by jomizrahi92** [comment]
That works for me. But if I click the test simulator beta and try it there I get the same response as my echo device.

**Comment by SConaway** [comment]
Huh.

**Comment by SConaway** [comment]
Would you mind sending a screenshot and I'll look at it tomorrow?

**Comment by jomizrahi92** [comment]
Now my simulator works all of a sudden when I type "ask garage to open" when previosuly I was writing "open garage" or "open garage door" but my Alexa does not. Attached screenshot.
![img_9641](https://user-images.githubusercontent.com/3697849/37036265-1fccbc70-211d-11e8-9395-abe2bc0fb478.PNG)

**Comment by SConaway** [comment]
Weird again. Can you find a log on AWS Lambda?

**Comment by jomizrahi92** [comment]
Ok I am extremely confused and I feel like an idiot.
Saying "ask garage to open" works
Saying any of the following gives an error:
"Ask **my** garage to open"
"Open garage"
"Open my garage"
- Same goes with replacing "garage" with "garage door"

Am I missing something? Shouldn't at least the others not give me a weird error but result in an error specifying the right way to be asked. I'm thinking now that the error I am getting might actually be the response of the welcome text or error text? And if so what am I missing?
Also how can I add it so all those sayings work?

**Comment by SConaway** [comment]
Ok. Can I get a screenshot of all Alexa Skills Dev Portal's tabs?

**Comment by jomizrahi92** [comment]
<img width="1392" alt="screen shot 2018-03-06 at 11 56 09 pm" src="https://user-images.githubusercontent.com/3697849/37074357-68150f0a-219a-11e8-8b7f-881202628e28.png">
<img width="1392" alt="screen shot 2018-03-06 at 11 56 02 pm" src="https://user-images.githubusercontent.com/3697849/37074358-6826dfd2-219a-11e8-8ba8-b67d2b5773a1.png">
<img width="1392" alt="screen shot 2018-03-06 at 11 55 28 pm" src="https://user-images.githubusercontent.com/3697849/37074359-68381eb4-219a-11e8-86e3-72790456c79c.png">
<img width="1392" alt="screen shot 2018-03-06 at 11 54 52 pm" src="https://user-images.githubusercontent.com/3697849/37074360-68508008-219a-11e8-99d8-6df8af7b7917.png">
<img width="1392" alt="screen shot 2018-03-06 at 11 54 34 pm" src="https://user-images.githubusercontent.com/3697849/37074361-68684bf2-219a-11e8-94ec-5e6f617c9b26.png">
<img width="1392" alt="screen shot 2018-03-06 at 11 52 41 pm" src="https://user-images.githubusercontent.com/3697849/37074362-6880a206-219a-11e8-855a-e21129349414.png">

**Comment by SConaway** [comment]
Try changing the app name to garage door. Dumb I know, but seems to help for me.

**Comment by jomizrahi92** [comment]
Changed only one saying works. But now its "doesn't support that" instead of "there was a problem".
But the "doesn't support that" doesn't seem to be built into the actual skill. So i'm not exactly sure still why its not registering correctly.
![image](https://user-images.githubusercontent.com/3697849/37134203-637c200c-2265-11e8-9f39-38c0c102c40a.png)

**Comment by SConaway** [comment]
I believe that is the intended functionality; A third party skill, such as this one, have to be 'asked' or 'told' to do something.

**Comment by jomizrahi92** [comment]
Interesting, alright thanks so much for all your help!
