### ISSUE TITLE
I am recieving an error when uploading the zip file for Function code. The error states "The file lambda_function.py could not be found. Make sure your handler upholds the format: file-name.method." Any ideas to resolve this

### ISSUE THREAD

**Issue by JustinSBlack** [jbnunn/Alexa-MyQGarage#39]
The error states "The file lambda_function.py could not be found. Make sure your handler upholds the format: file-name.method." Any ideas to resolve this?
Cheers.

**Comment by SConaway** [comment]
Can you show a screenshot?

**Comment by JustinSBlack** [comment]
Thanks Steven.
See the image below. 
![image](https://user-images.githubusercontent.com/13065120/37413139-fa783e86-276b-11e8-8c94-102382d3477b.png)

**Comment by SConaway** [comment]
I'd say change `lambda_function.lambda_handler` to `main.lambda_handler`

**Comment by JustinSBlack** [comment]
@SConaway 
Thank you so much! That was exactly the issue! Clearly I missed that in the documentation. Sorry
Thanks again for your help and the reply!

**Comment by jbnunn** [comment]
Slack 2FA codes to add to 1password:

·         119688880
·         355280686
·         996002464
·         983266868
·         475222080
·         033866424
·         011208606
·         310428088
·         637568006
·         091228246
