### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by SConaway** [jbnunn/Alexa-MyQGarage#6]
**This is the Log:**

START RequestId: 91599ffe-5c39-11e6-bbdd-5d14577d3be3 Version: $LATEST
'UserId': KeyError
Traceback (most recent call last):
  File "/var/task/main.py", line 31, in lambda_handler
    login()
  File "/var/task/main.py", line 94, in login
    myq_userid = response["UserId"]
KeyError: 'UserId'

END RequestId: 91599ffe-5c39-11e6-bbdd-5d14577d3be3
REPORT RequestId: 91599ffe-5c39-11e6-bbdd-5d14577d3be3  Duration: 440.80 ms Billed Duration: 500 ms     Memory Size: 128 MB Max Memory Used: 20 MB  

**This is the Lambada request i'm using:**

{
  "session": {
    "sessionId": "SessionId.dd449f7b-c202-4006-b1a1-0441b6f54942",
    "application": {
      "applicationId": "amzn1.ask.skill.f82eae7f-3c7f-476f-8ce7-41c7a15fc8f3"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.AFP3ZWPOS2BGJR7OWJZ3DHPKMOMJUHMBDZCXQSI4KAQ4MFH25X764YRBSUVLD6Y3RCK5XBUMJJRBJNWHNLG5YORXC35QM7RFVVY5TPPNSRAIE7NURINFZ74MHYLRJEFV3RASWXCHKX7PMZ6OD3GQGDZHO72AV3PJQGWN7VB2XIAHST5DFYRXKJK2J2JIBZ5BY622S7FLG22MXXA"
    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.d0ff9410-f895-455a-8ab2-903de173bad3",
    "locale": "en-US",
    "timestamp": "2016-08-06T18:35:57Z",
    "intent": {
      "name": "StateIntent",
      "slots": {
        "doorstate": {
          "name": "doorstate",
          "value": "down"
        }
      }
    }
  },
  "version": "1.0"
}

Code is attached

[Code.zip](https://github.com/jbnunn/Alexa-MyQGarage/files/405244/Code.zip)

**Comment by jbnunn** [comment]
@SConaway did you get this solved?

**Comment by SConaway** [comment]
Yes I did. Before Chamberlain updated their API, I made my own version, based off of @merkidemis [https://github.com/SConaway/Alexa-MyQGarage](url).  I Got your version working now.
