### ISSUE TITLE
Last steps?

### ISSUE THREAD

**Issue by brianwarehime** [jbnunn/Alexa-MyQGarage#9]
So, I went ahead and created this Skill and it works great through testing. Am I supposed to leave this in development state, just so I can use it? It looks like I need to get it certified and published, however, I have my ID's in the code, so that wouldn't work. 

Just wondering where I go after testing. Thanks!

**Comment by asimfaiz** [comment]
Hi Brianwarehime. 
I'm have been struggling with it for a few day and I cant even get the test. 
Was there a special way to zip the files., Lambda is giving me a syntaxerror.

**Comment by brianwarehime** [comment]
@asimfaiz I read the updated directions in https://github.com/jbnunn/Alexa-MyQGarage/pull/7 and that's the only thing I changed (in addition to the original instructions), and got it working. Also, after testing it successfully, I just left it alone, since it worked through the console and on my Alexa, so don't really need to publish it or anything.

**Comment by asimfaiz** [comment]
ok, ill try it, and yes you don't need to publish it. This is your personal skill

**Comment by asimfaiz** [comment]
Question please. Did you use notepad to edit the main.py file in order to change your user name and password.

**Comment by brianwarehime** [comment]
Yea, any text editor should do.

**Comment by asimfaiz** [comment]
Last question and I wont bother you again
How do I zip them. I only know how to zip using windows explorer. Any special way, 

Need help with the following instructions

zip -r lambda-upload.zip main.py requests requests-2.9.1.dist-info

**Comment by brianwarehime** [comment]
Hah, no worries! :)

If you're on Windows you'll need to do something like this:

"Locate the file or folder that you want to zip.
Press and hold (or right-click) the file or folder, select (or point to) Send to, and then select Compressed (zipped) folder.

A new zipped folder with the same name is created in the same location. To rename it, press and hold (or right-click) the folder, select Rename, and then type the new name."

If you're on a Mac, you can just run that command in the terminal when you're in the folder with all those files.

**Comment by asimfaiz** [comment]
Thanks I will try it. 
What threw me off was;

_"specific instructions are needed for creating the zip archive. You
  can't just zip up the parent directory"_

**Comment by asimfaiz** [comment]
Hi Brian, 
I successfully configured everything and was able speak the command and Alexa responses back "that the door is opened" BUT the door neither closes to opens. I don't see any errors in Lambda Logs
any suggestions

**Comment by mqbui1** [comment]
Asimfaiz, did you ever get this issue resolved?  I'm running into the same issue as you.  I'm able to issue the open and close command and Alexa responds to confirm but the garage doesn't actually open or close.

**Comment by mqbui1** [comment]
I also don't see any error messages from the logs.  I do see the print messages before the http request is sent.

**Comment by asimfaiz** [comment]
No the issue didn't resolve and no one responded so I gave up . 
Would love to get it working

**Comment by tigerbrain** [comment]
Hi @asimfaiz.  Is this still an issue for you?  Maybe adding some messages to the script may help better identify the problem you are facing.
